Theme=catppuccin-mocha-blue
DarkTheme=catppuccin-mocha-blue
UseDarkTheme=True
Font="Noto Sans CJK SC 13"
MenuFont="Noto Sans CJK SC 12"
Vertical Candidate List=False
WheelForPaging=True
EnableFractionalScale=True
